"""
apply_tier3_sourcing.py
--------------------------
Merges the 30-row Tier 3 sourced-data (tier3_sourced_data.json,
generated by build_tier3_sourced_data.py) into outputs/tier3_enriched.json,
populating MFR URL and SOURCE_TYPE for the matched rows only.

This is the Tier 3 parallel to apply_tier2_fixes.py (19 Aug). It does
NOT touch BRAND_NAME/MANUFACTURER_NAME -- that's enforce_manufacturer_
consistency.py's job. It only adds source-traceability fields.

Run (from project root):
    python scripts/apply_tier3_sourcing.py
"""

import json

SOURCED_DATA_PATHS = ["tier3_sourced_data.json", "tier3_sourced_data_batch2.json"]
TIER3_PATH = "outputs/tier3_enriched.json"


def main():
    sourced = {}
    for path in SOURCED_DATA_PATHS:
        with open(path, encoding="utf-8") as f:
            batch = json.load(f)
        sourced.update(batch)

    with open(TIER3_PATH, encoding="utf-8") as f:
        records = json.load(f)

    updated = 0
    mismatches_flagged = []

    for r in records:
        mpn = r.get("Mfg_Part_Num", "")
        if mpn not in sourced:
            continue

        entry = sourced[mpn]

        if entry.get("mfr_url"):
            r["MFR URL"] = entry["mfr_url"]
            r["SOURCE_TYPE"] = entry["source_type"]
            updated += 1

        if entry.get("brand_mismatch_flag"):
            mismatches_flagged.append({
                "mfg_part_num": mpn,
                "current_brand": r.get("BRAND_NAME"),
                "note": entry["brand_mismatch_flag"],
            })

    with open(TIER3_PATH, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2)

    print(f"Updated {updated} rows with MFR URL / SOURCE_TYPE in {TIER3_PATH}")
    print(f"Total Tier 3 rows: {len(records)}")

    if mismatches_flagged:
        print(f"\n⚠ {len(mismatches_flagged)} brand-mismatch findings (NOT auto-corrected, review needed):")
        for m in mismatches_flagged:
            print(f"  - {m['mfg_part_num']}: current BRAND_NAME='{m['current_brand']}' | {m['note']}")


if __name__ == "__main__":
    main()